### ISSUE TITLE
[HU00] Generar una buena estructura en la memoria

### ISSUE THREAD

**Issue by jero-dev** [jero-dev/proyecto-tfg#2]
## Historia de usuario

Como tribunal de TFG, necesito entender todos los términos que figuran en el TFG, entender claramente cuál es la aportación del estudiante, y los retos que ha superado. Y quiero verlo por escrito en un informe que esté correctamente escrito, tenga el formato correcto, y exprese claramente el trabajo realizado.

Además, valoraré que el estudiante:

- Utilice fuentes de información variadas, válidas y fiables y selecciona la relevante para el objetivo del trabajo.
- Tome decisiones adecuadas al contexto y propone soluciones utilizando el conocimiento adquirido.
- Detecte y analice oportunidades para hacer nuevas propuestas.
- Propone soluciones adecuadas y justifica las decisiones tomadas para resolver problemas complejos.
- Utilice recursos formales e informales para documentar adecuadamente el proceso de desarrollo: concepción, planificación, análisis, diseño, implementación, pruebas, etc.
- Muestre claridad y comprensión en la redacción, organizando la información adecuadamente y utilizando los recursos adecuados para el discurso escrito.
- Muestre claridad y comprensión en la expresión oral, organizando la información adecuadamente y utilizando los recursos adecuados para el discurso oral.
- Cree un proyecto lo suficientemente complejo.

**Comment by JJ** [comment]
Este cliente necesita algo más que la memoria, pero la memoria evidentemente es sólo para él. Por otro lado, convendría que incluuyeras [los criterios de evaluación](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/8) para entender qué es lo que busca este cliente y cómo va a evaluarlo.

**Comment by jero-dev** [comment]
Esta historia se puede cerrar con la finalización de la redacción de la memoria del proyecto.
