### ISSUE TITLE
Obtener los mensajes de un canal mediante un bot de Telegram

### ISSUE THREAD

**Issue by jero-dev** [jero-dev/proyecto-tfg#23]
Debemos de obtener los mensajes de un canal de ofertas para poder seguir con el desarrollo de nuestro proyecto.

Esta issue está relacionada con la Historia de Usuario #9 [HU01] Obtener la oferta más reciente para un producto

**Comment by JJ** [comment]
Quizás deberías hacer antes un análisis del problema mediante DDD. Si obtienes las ofertas, tendrás que incluirlas en alguna estructura de datos, y para diseñar esa estructura de datos necesitas analizar el problema.
