### ISSUE TITLE
Analizar el problema usando diseño dirigido por dominios

### ISSUE THREAD

**Issue by jero-dev** [jero-dev/proyecto-tfg#25]
Para un mejor entendimiento del problema necesitamos analizarlo. Además, para saber en qué debemos de centrarnos y encontrar el foco, la mejor manera de hacerlo es usando la metodología de diseño dirigido por dominios

Esta tarea está relacionada con la historia de usuario #2 [HU00] Generar una buena estructura en la memoria

**Comment by JJ** [comment]
Esto sería mejor que lo convirtieras en milestone. Un issue tiene que plantear un problema, y en este caso no estás haciendo eso, sino planteando una tarea. En el milestone que crees deberías poner todos los issues que se creen durante la modelización del problema, analizando las historias de usuario.
En todo caso, no encaja ni por temática dentro del milestone que está ahora.
