### ISSUE TITLE
El problema debe de describirse en la memoria de manera clara y concisa

### ISSUE THREAD

**Issue by jero-dev** [jero-dev/proyecto-tfg#5]
Para poder seguir con el proyecto, necesitamos tener la descripción del problema con su solución en la memoria. A grandes rasgos sería:

- Problema: En un canal de ofertas es difícil seguir el hilo de los productos que nos interesan.
- Solución: Un resumidor que nos dé información actualizada del producto en el que estamos interesados.

Issue relacionada con #2 [HU00] Generar una buena estructura en la memoria

**Comment by JJ** [comment]
REcuerda que los isssues plantean problemas "El problema tiene que estar claramente definido", por ejemplo

**Comment by JJ** [comment]
Todos los issues tienen que estar también relacionados con una HU; los PRs referencian solamente issues, no historias de usuario.
