### ISSUE TITLE
No existe una estructura básica de la API

### ISSUE THREAD

**Issue by jero-dev** [jero-dev/proyecto-tfg#7]
Antes de seguir desarrollando, hay que crear un esqueleto para que sea más fácil el seguimiento del desarrollo.

Esta issue está relacionada con #9 [HU01] Obtener la oferta más reciente para un producto

**Comment by JJ** [comment]
Esto también sería un milestone; las historias de usuario deben estar siempre en el dominio del problema y contadas desde el punto de vista del usuario

**Comment by JJ** [comment]
Cada issue tiene que representar un problema, no una tarea. Además, tienes que tratar que los issues estén asignados a PMVs de complejidad creciente.
