### ISSUE TITLE
No hay una planificación definida en la documentación

### ISSUE THREAD

**Issue by jero-dev** [jero-dev/proyecto-tfg#8]
En la documentación aún no existe una sección de planificación del proyecto. 

Para tener una planificación bien estructurada, necesitamos redactar:

- [x] Metodologías utilizadas
- [ ] Usuarios o *stakeholders* identificados
- [ ] Historias de usuario
- [x] Seguimiento del proyecto

Esta tarea está relacionada con la historia de usuario #2

**Comment by JJ** [comment]
Esto no es una historia de usuario, simplemente tienes que hacerlo para avanzar el milestone

**Comment by JJ** [comment]
El issue que has hecho no contiene la planificación, en el sentido de todos los milestones. Los milestones, además, tienen dos problemas
1. Representan saltos muy grandes (del 0 al 1, por ejemplo)
2. No están bien ordenados: tienen niveles de abstracción superiores (como el API) antes que otros inferiores (como leer de los APIs de Discord y Telegram)
3. Los milestones tienen que definir productos mínimamente viables.
4. Las HUs no se asignan a milestones.

Por eso, dejo esto abierto porque tienes que redefinir los milestones tanto aquí como escribirlo en la documentación.

**Comment by JJ** [comment]
Mirando a #22 es posible que sea mejor no incluir los milestones en la planificación, porque eso puede dar lugar a duplicados. La planificación en el capítulo dedicada a la misma debe explicar cómo se decide el siguiente milestones y el hecho de que se vayan a usar milestones solamente. En general, en desarrollo ágil tampoco se hace una planificación en PMVs fija de antemano.

**Comment by jero-dev** [comment]
Entonces, teniendo esto en cuenta, podemos cerrar esta issue, ¿no?

**Comment by JJ** [comment]
Los milestones tienes que incluirlos, sólo que en otro capítulo.

**Comment by JJ** [comment]
Por aclarar un poco, los milestones *iniciales* irían en el capítulo inicial de planificación, y los siguientes en el de implementación. En desarrollo ágil los milestones no se pueden planificar todos desde el principio
